language: c
os:
    - osx
#    - linux
compiler:
    - clang
#   - gcc
install: 
    - pwd
    - ls
    - mkdir -p build
    - cd build
    - wget -q http://embedthis.com/software/makeme-0.10.0-src.tgz -O makeme.tgz
    - tar xvfz makeme.tgz
    - cd makeme-*
    - make boot 
    - sudo make install
    - cd ../..
    - pwd
    - which me
script:
    - echo SCRIPT
    - pwd
    - ls
    - ./configure
    - me
    - me test

# notifications:


#addons:
#  ssh_known_hosts:
#  - git.example.com
#  - 111.22.33.44

# after_success:
# - me package
# - me upload

